#!/usr/bin/env python3
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]

def run(*args):
    print("$", " ".join(map(str, args)))
    subprocess.run(args, cwd=ROOT, check=True)

run(sys.executable, "scripts/build_figures.py")
run(sys.executable, "scripts/check_quantum_readout.py")
run(sys.executable, "scripts/audit_resolved_record_history_interface.py")
run(sys.executable, "scripts/audit_tensor_factorization.py")
run(sys.executable, "scripts/audit_standard_recovery_and_discriminator.py")
run(sys.executable, "scripts/audit_public_qgt_evidence.py")
run(sys.executable, "scripts/audit_public_carrier_census.py")
run(sys.executable, "scripts/audit_ness2021_qor_control.py")
run(sys.executable, "scripts/audit_two_band_spectral_qgt_independence.py")
run(sys.executable, "scripts/audit_susceptibility_moment_no_go.py")
run(sys.executable, "scripts/audit_local_stiffness_finite_distance_no_go.py")
run(sys.executable, "scripts/audit_endpoint_holonomy_no_go.py")
run(sys.executable, "scripts/audit_alternative_source_census.py")
run(sys.executable, "scripts/audit_joint_qubit_source_model.py")
run(sys.executable, "scripts/score_alternative_source_readiness.py")
run(sys.executable, "scripts/audit_resonator_axis.py")
run(sys.executable, "scripts/audit_generalized_force_independence.py")
run(sys.executable, "scripts/audit_public_source_port_candidates.py")
run(sys.executable, "scripts/audit_chdf_body_work_source.py")
run(sys.executable, "scripts/audit_chdf_uhlmann_range_and_selection.py")
run(sys.executable, "scripts/audit_depolarizing_recovery_selector.py")
run(sys.executable, "scripts/audit_protected_logical_recovery_split.py")
run(sys.executable, "scripts/audit_root_commutant_factorization.py")
run(sys.executable, "scripts/audit_root_factor_designation_no_go.py")
run(sys.executable, "scripts/audit_extremal_observer_access_selector.py")
run(sys.executable, "scripts/audit_qubit_terminal_minimality_selector.py")
run(sys.executable, "scripts/audit_observer_noise_commutant_selector.py")
run(sys.executable, "scripts/audit_canonical_expectation_complement.py")
run(sys.executable, "scripts/audit_regular_event_factor_selection.py")
run(sys.executable, "scripts/audit_approximate_factor_selection_bound.py")
run(sys.executable, "scripts/audit_central_chirality_terminal_blindness.py")
run(sys.executable, "scripts/audit_joint_quantum_packet_parent_selection.py")
run(sys.executable, "scripts/audit_isolated_logical_nonleakage_selector.py")
run(sys.executable, "scripts/audit_source_hypergraph_isolation.py")
run(sys.executable, "scripts/audit_disjoint_source_valuation.py")
run(sys.executable, "scripts/audit_parent_valuation_lift.py")
run(sys.executable, "scripts/audit_future_extension_quantum_carrier.py")
run(sys.executable, "scripts/audit_future_extension_covariant_phase_space.py")
run(sys.executable, "scripts/audit_irreducible_future_mode_scale_lock.py")
run(sys.executable, "scripts/audit_future_root_irreducibility_bridge.py")
run(sys.executable, "scripts/audit_mixed_boundary_future_root_source.py")
run(sys.executable, "scripts/audit_brac_vs_boundary_bridge_activation.py")
run(sys.executable, "scripts/audit_covariant_kinetic_boundary_activation.py")
run(sys.executable, "scripts/audit_record_conditioned_future_fluidity.py")
run(sys.executable, "scripts/audit_bounded_future_possibility_body.py")
run(sys.executable, "scripts/audit_concrete_body_root_rank_eligibility.py")
run(sys.executable, "scripts/score_naghiloo_candidate.py")
run(sys.executable, "scripts/score_cottet_candidate.py")
run(sys.executable, "scripts/audit_cottet_fluctuation_novelty.py")
run(sys.executable, "scripts/audit_public_single_shot_candidates.py")
run(sys.executable, "scripts/score_optical_path_integral_candidate.py")
run(sys.executable, "scripts/audit_joint_path_data_candidates.py")
run(sys.executable, "scripts/score_reconstructed_optical_path_morphology.py")
run(sys.executable, "scripts/audit_wen_figs2b_phase_control.py")
run(sys.executable, "scripts/score_published_optical_amplitude_morphology.py")
run(sys.executable, "scripts/score_tau_frozen_path_curvature_candidate.py")
run("tectonic", "paperVI_submission_source/main.tex")
run("tectonic", "paperVI_submission_source/public_data_audit_supplement.tex")
run(sys.executable, "scripts/build_arxiv_source.py")
run(sys.executable, "-m", "pytest", "-q")
print("FOUNDATION_PAPER_VI_REPRODUCTION_COMPLETE")
